services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  password
      MYSQL_DATABASE: sports_shop
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sports_shop
  mongo:
    image: mongo:8.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sports_shop
    volumes:
      - mongodata:/data/db
    networks:
      - sports_shop
volumes:
  mysql_data:
  mongodata:

networks:
  sports_shop: